### ISSUE TITLE
What is clipboardRead permission for?

### ISSUE THREAD

**Issue by Tbaut** [palerdot/remindoro#19]
Hello and thank you very much for this extension. May I know why the extension needs `clipboardRead` permission?
edit: I see it's in https://github.com/palerdot/remindoro/blob/656d8364ef841b3473ae720da0527f3bfe0a1a15/app/js/general-initializer.js#L23 to prevent pasting html.

This is quite an important permission in terms of security though, would you accept a PR to remove this? I can think of other ways to prevent what you want, such as escaping any html char.

**Comment by palerdot** [comment]
> May I know why the extension needs clipboardRead permission?
It is needed because you can save a reminder from *clipboard selection*. Like right click on selection and save it as reminder.

That said, I might soon revamp this whole codebase during which I might remove unwanted permission. But I guess, `clipboarRead` might be needed to save reminders from clipboard selection.
